### ISSUE TITLE
服务端[Forward]建立Swap超时，过一短时间崩溃

### ISSUE THREAD

**Issue by shanyanwt** [SpringHgui/FastTunnel#39]
客户端和服务端可以正常链接使用
Server linux-64
client window-x64
版本 #V2.04
当tcp转发后
`info: FastTunnel.Core.Handlers.Server.LoginHandler[0]
      【0.0.0.0:1003】Accepted. There are 1 clients connected to the port
info: FastTunnel.Core.Handlers.Server.LoginHandler[0]
      【0.0.0.0:1003】Accepted. There are 2 clients connected to the port
fail: FastTunnel.Core.Handlers.Server.LoginHandler[0]
      [Forward]建立Swap超时 2c191d25fa87402a9****
fail: FastTunnel.Core.Handlers.Server.LoginHandler[0]
      [Forward]建立Swap超时 1654a546e2414baa9****`
过段时间客户端链接超时
客户端链接超时 The remote party closed the WebSocket connection without completing the close handshake.
服务端报错提示
`info: FastTunnel.Core.Handlers.Server.LoginHandler[0]
      【0.0.0.0:1003】Accepted. There are 1 clients connected to the port
info: FastTunnel.Core.Handlers.Server.LoginHandler[0]
      【0.0.0.0:1003】Accepted. There are 2 clients connected to the port
fail: FastTunnel.Core.Handlers.Server.LoginHandler[0]
      [Forward]建立Swap超时 2c191d25fa87402a9****
fail: FastTunnel.Core.Handlers.Server.LoginHandler[0]
      [Forward]建立Swap超时 1654a546e2414baa9****

fail: FastTunnel.Core.MiddleWares.FastTunnelClientHandler[0]
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at FastTunnel.Core.Forwarder.MiddleWare.FastTunnelSwapHandler.Handle(HttpContext context, Func`1 next) in E:\Github\FastTunnel\FastTunnel.Core\Forwarder\MiddleWare\FastTunnelSwapHandler.cs:line 65
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[0]
      Unexpected exception in SocketConnection.CancelConnectionClosedToken.
      System.AggregateException: One or more errors occurred. (An attempt was made to transition a task to a final state when it had already completed.)
       ---> System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
         at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
         at FastTunnel.Core.Forwarder.MiddleWare.FastTunnelSwapHandler.<>c.<Handle>b__3_0(Object task) in E:\Github\FastTunnel\FastTunnel.Core\Forwarder\MiddleWare\FastTunnelSwapHandler.cs:line 62
         at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         --- End of inner exception stack trace ---
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
         at System.Threading.CancellationTokenSource.Cancel()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.CancelConnectionClosedToken()
fail: FastTunnel.Core.MiddleWares.FastTunnelClientHandler[0]
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at FastTunnel.Core.Forwarder.MiddleWare.FastTunnelSwapHandler.Handle(HttpContext context, Func`1 next) in E:\Github\FastTunnel\FastTunnel.Core\Forwarder\MiddleWare\FastTunnelSwapHandler.cs:line 65
fail: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[0]
      Unexpected exception in SocketConnection.CancelConnectionClosedToken.
      System.AggregateException: One or more errors occurred. (An attempt was made to transition a task to a final state when it had already completed.)
       ---> System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
         at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
         at FastTunnel.Core.Forwarder.MiddleWare.FastTunnelSwapHandler.<>c.<Handle>b__3_0(Object task) in E:\Github\FastTunnel\FastTunnel.Core\Forwarder\MiddleWare\FastTunnelSwapHandler.cs:line 62
         at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         --- End of inner exception stack trace ---
         at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
         at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
         at System.Threading.CancellationTokenSource.Cancel()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.CancelConnectionClosedToken()
`

**Comment by SpringHgui** [comment]
该问题已修复
