### ISSUE TITLE
Reading is already in progress. 

### ISSUE THREAD

**Issue by SpringHgui** [SpringHgui/FastTunnel#59]
```
[10:38:52 INF] Executed endpoint 'Fallback {*path:nonfile}'
[10:38:52 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - - - 200 - - 0.1739ms
[10:38:58 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - -
[10:38:58 INF] Executing endpoint 'Fallback {*path:nonfile}'
[10:38:58 INF] Executed endpoint 'Fallback {*path:nonfile}'
[10:38:58 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - - - 200 - - 0.1727ms
[10:38:59 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - -
[10:38:59 INF] Executing endpoint 'Fallback {*path:nonfile}'
[10:38:59 INF] Executed endpoint 'Fallback {*path:nonfile}'
[10:38:59 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - - - 200 - - 0.1560ms
[10:39:00 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - -
[10:39:00 INF] Executing endpoint 'Fallback {*path:nonfile}'
[10:39:00 INF] Executed endpoint 'Fallback {*path:nonfile}'
[10:39:00 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - - - 200 - - 0.2077ms
[10:39:00 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - -
[10:39:00 INF] Executing endpoint 'Fallback {*path:nonfile}'
[10:39:00 INF] Executed endpoint 'Fallback {*path:nonfile}'
[10:39:00 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - - - 200 - - 0.2032ms
[10:39:01 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - -
[10:39:01 INF] Executing endpoint 'Fallback {*path:nonfile}'
[10:39:01 INF] Executed endpoint 'Fallback {*path:nonfile}'
[10:39:01 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - - - 200 - - 0.1733ms
[10:39:01 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - -
[10:39:01 INF] Executing endpoint 'Fallback {*path:nonfile}'
[10:39:01 INF] Executed endpoint 'Fallback {*path:nonfile}'
[10:39:01 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/pos/Test - - - 200 - - 0.2103ms
[11:57:10 INF] 客户端关闭  ::ffff:61.140.25.26 当前在线数：0
[11:57:10 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/ - - - 101 - - 4920014.8848ms
[15:22:14 ERR] Unhandled exception while processing 0HMP67I1HU77G.
System.InvalidOperationException: Reading is already in progress.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at FastTunnel.Core.Forwarder.FastTunelProtocol.TryAnalysisPipeAsync() in /src/FastTunnel.Core/Forwarder/FastTunelProtocol.cs:line 52
   at FastTunnel.Core.Forwarder.Kestrel.MiddleWare.InitializerMiddleware.OnConnectionAsync(ConnectionContext context) in /src/FastTunnel.Core/Forwarder/Kestrel/MiddleWare/InitializerMiddleware.cs:line 37
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
[06:20:12 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/ - -
[06:20:12 INF] 客户端连接 ::ffff:61.140.25.26 当前在线数：1
[06:22:29 ERR] Unhandled exception while processing 0HMP67I1HU77O.
System.InvalidOperationException: Reading is already in progress.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at FastTunnel.Core.Forwarder.FastTunelProtocol.TryAnalysisPipeAsync() in /src/FastTunnel.Core/Forwarder/FastTunelProtocol.cs:line 52
   at FastTunnel.Core.Forwarder.Kestrel.MiddleWare.InitializerMiddleware.OnConnectionAsync(ConnectionContext context) in /src/FastTunnel.Core/Forwarder/Kestrel/MiddleWare/InitializerMiddleware.cs:line 37
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
[06:22:32 ERR] Unhandled exception while processing 0HMP67I1HU77P.
System.InvalidOperationException: Reading is already in progress.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at FastTunnel.Core.Forwarder.FastTunelProtocol.TryAnalysisPipeAsync() in /src/FastTunnel.Core/Forwarder/FastTunelProtocol.cs:line 52
   at FastTunnel.Core.Forwarder.Kestrel.MiddleWare.InitializerMiddleware.OnConnectionAsync(ConnectionContext context) in /src/FastTunnel.Core/Forwarder/Kestrel/MiddleWare/InitializerMiddleware.cs:line 37
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
[06:22:34 ERR] Unhandled exception while processing 0HMP67I1HU77Q.
System.InvalidOperationException: Reading is already in progress.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at FastTunnel.Core.Forwarder.FastTunelProtocol.TryAnalysisPipeAsync() in /src/FastTunnel.Core/Forwarder/FastTunelProtocol.cs:line 52
   at FastTunnel.Core.Forwarder.Kestrel.MiddleWare.InitializerMiddleware.OnConnectionAsync(ConnectionContext context) in /src/FastTunnel.Core/Forwarder/Kestrel/MiddleWare/InitializerMiddleware.cs:line 37
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
[06:23:20 INF] Starting up!
[06:23:20 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
[06:23:20 INF] User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
[06:23:20 WRN] Overriding address(es) 'http://*:1270'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
[06:23:20 INF] Now listening on: http://[::]:1270
[06:23:20 INF] Application started. Press Ctrl+C to shut down.
[06:23:20 INF] Hosting environment: Production
[06:23:20 INF] Content root path: /app
[06:23:29 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/ - -
[06:23:29 INF] 客户端连接 ::ffff:61.140.25.26 当前在线数：1
[06:23:34 ERR] Unhandled exception while processing 0HMPC614CNJ9O.
System.InvalidOperationException: Reading is already in progress.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at FastTunnel.Core.Forwarder.FastTunelProtocol.TryAnalysisPipeAsync() in /src/FastTunnel.Core/Forwarder/FastTunelProtocol.cs:line 52
   at FastTunnel.Core.Forwarder.Kestrel.MiddleWare.InitializerMiddleware.OnConnectionAsync(ConnectionContext context) in /src/FastTunnel.Core/Forwarder/Kestrel/MiddleWare/InitializerMiddleware.cs:line 33
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
[06:23:35 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/ - -
[06:23:35 INF] Executing endpoint 'Fallback {*path:nonfile}'
[06:23:35 INF] Executed endpoint 'Fallback {*path:nonfile}'
[06:23:35 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/ - - - 200 - - 6.5813ms
[06:23:36 INF] Request starting HTTP/1.1 GET http://8.134.14.93:1270/favicon.ico - -
[06:23:36 INF] Request finished HTTP/1.1 GET http://8.134.14.93:1270/favicon.ico - - - 404 0 - 2.5841ms
[06:23:37 ERR] Unhandled exception while processing 0HMPC614CNJ9Q.
System.InvalidOperationException: Reading is already in progress.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at FastTunnel.Core.Forwarder.FastTunelProtocol.TryAnalysisPipeAsync() in /src/FastTunnel.Core/Forwarder/FastTunelProtocol.cs:line 52
   at FastTunnel.Core.Forwarder.Kestrel.MiddleWare.InitializerMiddleware.OnConnectionAsync(ConnectionContext context) in /src/FastTunnel.Core/Forwarder/Kestrel/MiddleWare/InitializerMiddleware.cs:line 33
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()

```

**Comment by SpringHgui** [comment]
v3版本问题，目前将主要维护v2版本，v3版本仅作为一种技术上的尝鲜
